name: "Bug Report"
description: "Use this template to report bugs or issues with Be Quiet Negotiator."
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: "textarea"
    attributes:
      label: "Description"
      description: "Give a concise description of the problem"
    validations:
      required: true
  - type: "input"
    attributes:
      label: "Version"
      description: "What version of Be Quiet Negotiator are you using?"
    validations:
      required: true
  - type: "input"
    attributes:
      label: "Minecraft and NeoForge Version"
      description: "What Minecraft and NeoForge version are you using?"
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "Expected outcome"
      description: "What did you expect to happen instead?"
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "Minimal Reproducible Example"
      description: "Provide instructions that can be followed to reproduce the issue"
    validations:
      required: true
  - type: "textarea"
    attributes:
      label: "Logs or Crash Report"
      description: "Provide a link to a log file or crash report. You must provide a latest.log, debug.log, and a crash report unless not applicable. You must use a service like https://mclo.gs/, https://gist.github.com rather than pasting the logs directly into the issue."
    validations:
      required: true